"""create orders

Revision ID: 16fc68e0d551
Revises: 1c10ef82df12
Create Date: 2026-02-08 22:42:22.297877

"""

# revision identifiers, used by Alembic.
revision = "16fc68e0d551"
down_revision = "1c10ef82df12"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
