"""create orders

Revision ID: 1c10ef82df12
Revises: 89d3eff846a7
Create Date: 2026-02-08 22:34:55.838683

"""

# revision identifiers, used by Alembic.
revision = '1c10ef82df12'
down_revision = '89d3eff846a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
