"""create payments

Revision ID: 8b9b03f4571f
Revises: f7f383f98fa2
Create Date: 2026-02-09 00:24:45.033390

"""

# revision identifiers, used by Alembic.
# --- header ---
revision = "8b9b03f4571f"
down_revision = "16fc68e0d551"
branch_labels = None
depends_on = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
