"""create payments

Revision ID: 99f5a7f50fa4
Revises: 8b9b03f4571f
Create Date: 2026-02-09 00:43:54.634586

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '99f5a7f50fa4'
down_revision = '8b9b03f4571f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'])
    op.alter_column('orders', 'status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'CREATED'::character varying"))
    op.drop_constraint('orders_idempotency_key_key', 'orders', type_='unique')
    op.drop_column('orders', 'idempotency_key')
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('payments', 'provider',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text("'fakepay'::character varying"))
    op.alter_column('payments', 'idempotency_key',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=120),
               existing_nullable=True)
    op.drop_constraint('payments_order_id_fkey', 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key('payments_order_id_fkey', 'payments', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('payments', 'idempotency_key',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=128),
               existing_nullable=True)
    op.alter_column('payments', 'provider',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("'fakepay'::character varying"))
    op.alter_column('payments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False)
    op.add_column('orders', sa.Column('idempotency_key', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_unique_constraint('orders_idempotency_key_key', 'orders', ['idempotency_key'])
    op.alter_column('orders', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=24),
               existing_nullable=False,
               existing_server_default=sa.text("'CREATED'::character varying"))
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
